name: Setup
description: Setup node, bun, etc.

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.2.0

    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - run: bun install
      shell: bash
