name: issue close

on:
  issues:
    types:
      - labeled

jobs:
  wontfix:
    runs-on: ubuntu-latest

    if: contains(github.event.issue.labels.*.name, 'wontfix')

    permissions:
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [],
              state: 'closed'
            })
